// GAME DATA
export const colors = {
  grey:        '#9D9D9D',
  green:       '#1EFF00',
  blue:        '#0070DD',
  white:       '#FFFFFF',
  purple:      '#A335EE',
  orange:      '#FF8000',
  artifact:    '#E6CC80',
  blizz:       '#00CCFF',
  deathKnight: '#C41F3B',
  druid:       '#FF7D0A',
  hunter:      '#ABD473',
  mage:        '#69CCF0',
  monk:        '#00FF96',
  paladin:     '#F58CBA',
  priest:      '#FFFFFF',
  rogue:       '#FFF569',
  shaman:      '#0070DE',
  warlock:     '#9482C9',
  warrior:     '#C79C6E',
  gold:        '#FCD60F',
  silver:      '#C0C0C0',
  copper:      '#FFA45B',
}

export const rank = colors.rank = [
  colors.white,
  colors.green,
  colors.blue,
  colors.purple,
  colors.orange,
  colors.artifact,
]

export const quality = colors.quality = [
  colors.grey,
  colors.white,
  colors.green,
  colors.blue,
  colors.purple,
  colors.orange,
  colors.artifact,
]

export const bitFlags = list => {
  const ret = list.map((name, index) => ({
    value: Math.pow(2, index),
    index,
    name,
  })).filter(n => Boolean(n.name))

  ret.bitFlags = true
  return ret
}

export const getCost = cost => [
  ['gold', Math.floor(cost / 10000)],
  ['silver', Math.floor((cost % 10000) / 100)],
  ['copper', Math.floor(cost % 100)],
].filter(([,v]) => v)

export const sortQuest = (a, b) => (b.QuestLevel - a.QuestLevel) || a.Title.localeCompare(b.Title)

export const classes = bitFlags([
 'Warrior',
 'Paladin',
 'Hunter',
 'Rogue',
 'Priest',
 'Death Knight',
 'Shaman',
 'Mage',
 'Warlock',
 'Druid',
])

export const dmgTypes = [
  'Physical',
  'Holy',
  'Fire',
  'Nature',
  'Frost',
  'Shadow',
  'Arcane',
]

export const race = bitFlags([
  'Human',
  'Orc',
  'Dwarf',
  'Night Elf',
  'Undead',
  'Tauren',
  'Gnome',
  'Troll',
  '', // Goblin
  'Blood Elf',
  'Draenei',
])

export const powerType = [
  'Mana',
  'Rage',
  '',
  'Energy',
]

export const skill = {
  164: 'Blacksmithing',
  165: 'Leatherworking',
  171: 'Alchemy',
  185: 'Cooking',
  186: 'Mining',
  197: 'Tailoring',
  202: 'Engineering',
  356: 'Fishing',
  755: 'Jewelcrafting',
  333: 'Enchanting',
  129: 'First Aid',
  182: 'Herbalism',
  633: 'Lockpicking',
  393: 'Skinning',
}

export const reputation = {
  21: 'Booty Bay',
  67: 'Horde',
  87: 'Bloodsail Buccaneers',
  270: 'Zandalar Tribe',
  469: 'Alliance',
  576: 'Timbermaw Hold',
  889: 'Warsong Outriders',
  890: 'Silverwing Sentinels',
}

export const faction = {
  120: 'Booty Bay',
  119: 'Bloodsail Buccaneers',
  16: 'Hostile',
  // 92: 'Gelkis Clan Centaur',
  // 93: 'Magram Clan Centaur',
  // 59: 'Thorium Brotherhood',
  // 349: 'Ravenholdt',
  // 70: 'Syndicate',
  // 369: 'Gadgetzan',
  // 471: 'Wildhammer Clan',
  // 470: 'Ratchet',
  // 169: 'Steamwheedle Cartel',
  // 529: 'Argent Dawn',
  // 76: 'Orgrimmar',
  // 530: 'Darkspear Trolls',
  // 81: 'Thunder Bluff',
  // 68: 'Undercity',
  // 54: 'Gnomeregan Exiles',
  // 72: 'Stormwind',
  // 47: 'Ironforge',
  // 69: 'Darnassus',
  // 86: 'Leatherworking – Dragonscale',
  // 83: 'Leatherworking – Elemental',
  // 549: 'Leatherworking – Tribal',
  // 551: 'Engineering – Gnome',
  // 550: 'Engineering – Goblin',
  // 589: 'Wintersaber Trainers',
  // 577: 'Everlook',
  // 46: 'Blacksmithing – Armorsmithing',
  // 289: 'Blacksmithing – Weaponsmithing',
  // 570: 'Blacksmithing – Axesmithing',
  // 571: 'Blacksmithing – Swordsmithing',
  // 569: 'Blacksmithing – Hammersmithing',
  // 574: 'Caer Darrow',
  // 609: 'Cenarion Circle',
  // 947: 'Thrallmar',
  // 946: 'Honor Hold',
  // 935: 'The Sha’tar',
  // 730: 'Stormpike Guard',
  // 729: 'Frostwolf Clan',
  // 749: 'Hydraxian Waterlords',
  // 980: 'The Burning Crusade',
  // 809: 'Shen’dralar',
  // 891: 'Alliance Forces',
  // 892: 'Horde Forces',
  // 930: 'Exodar',
  // 909: 'Darkmoon Faire',
  // 510: 'The Defilers',
  // 509: 'The League of Arathor',
  // 910: 'Brood of Nozdormu',
  // 911: 'Silvermoon City',
  // 922: 'Tranquillien',
  // 990: 'The Scale of the Sands',
  // 932: 'The Aldor',
  // 936: 'Shattrath City',
  // 933: 'The Consortium',
  // 941: 'The Mag’har',
  // 934: 'The Scryers',
  // 967: 'The Violet Eye',
  // 942: 'Cenarion Expedition',
  // 970: 'Sporeggar',
  // 978: 'Kurenai',
  // 989: 'Keepers of Time',
  // 1005: 'Friendly, Hidden',
  // 1011: 'Lower City',
  // 1012: 'Ashtongue Deathsworn',
  // 1015: 'Netherwing',
  // 1031: 'Sha’tari Skyguard',
  // 1038: 'Ogri’la',
  // 1050: 'Valiance Expedition',
  // 1052: 'Horde Expedition',
  // 1064: 'The Taunka',
  // 1067: 'The Hand of Vengeance',
  // 1068: 'Explorers’ League',
  // 1073: 'The Kalu’ak',
  // 1077: 'Shattered Sun Offensive',
  // 1085: 'Warsong Offensive',
  // 1091: 'The Wyrmrest Accord',
  // 1090: 'Kirin Tor',
  // 1037: 'Alliance Vanguard',
  // 1097: 'Wrath of the Lich King',
  // 1094: 'The Silver Covenant',
  // 1098: 'Knights of the Ebon Blade',
  // 1104: 'Frenzyheart Tribe',
  // 1105: 'The Oracles',
  // 1106: 'Argent Crusade',
  // 1117: 'Sholazar Basin',
  // 1118: 'Classic',
  // 1119: 'The Sons of Hodir',
  // 1124: 'The Sunreavers',
  // 1126: 'The Frostborn',
  // 1136: 'Tranquillien Conversion',
  // 1137: 'Wintersaber Conversion',
  // 1154: 'Silver Covenant Conversion',
  // 1155: 'Sunreavers Conversion',
  // 1156: 'The Ashen Verdict',
}
