const color = module.exports = {
  background:    '#282A36',
  selection:     '#44475A',
  foreground:    '#F8F8F2',
  comment:       '#6272A4',
  cyan:          '#8BE9FD',
  green:         '#50FA7B',
  orange:        '#FFB86C',
  pink:          '#FF79C6',
  purple:        '#BD93F9',
  red:           '#FF5555',
  yellow:        '#F1FA8C',
  blizz: {
    grey:        '#9D9D9D',
    green:       '#1EFF00',
    blue:        '#0070DD',
    white:       '#FFFFFF',
    purple:      '#A335EE',
    orange:      '#FF8000',
    artifact:    '#E6CC80',
    blizz:       '#00CCFF',
    deathKnight: '#C41F3B',
    druid:       '#FF7D0A',
    hunter:      '#ABD473',
    mage:        '#69CCF0',
    monk:        '#00FF96',
    paladin:     '#F58CBA',
    priest:      '#FFFFFF',
    rogue:       '#FFF569',
    shaman:      '#0070DE',
    warlock:     '#9482C9',
    warrior:     '#C79C6E',
    gold:        '#FCD60F',
    silver:      '#C0C0C0',
    copper:      '#FFA45B',
  }
}

color.blizz.rank = [
  color.blizz.white,
  color.blizz.green,
  color.blizz.blue,
  color.blizz.purple,
  color.blizz.orange,
  color.blizz.artifact,
]

color.blizz.quality = [
  color.blizz.grey,
  color.blizz.white,
  color.blizz.green,
  color.blizz.blue,
  color.blizz.purple,
  color.blizz.orange,
  color.blizz.artifact,
]
